# Site settings | 网站设置
title: onlykk
SEOTitle: 白小凯的博客 | onlykk
header-img: img/top_bg_home.jpg
email: xkkbai@163.com
description: "白小凯的博客"
keyword: "onlykk, 白小凯的博客, 白小凯, onlykk, Android"
url: "http://onlykk.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/onlykk/onlykk.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "愿一路都有好风景！"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
github_username: onlykk
csdn_username: ximen_qing
maimai_username: 白小凯
linkin_username: 白小凯




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 1675c22923c74e399e8e                            #生成的clientID
  clientSecret: 9d7a97297ac73a483211f95a15197d8f53039a80    #生成的clientSecret
  repo: onlykk.github.io    #仓库名称
  owner: onlykk    # github用户名
  admin: onlykk
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·onlykk",
        href: "http://onlykk.github.io"
    },{
        title: "CSDN·西门庆",
        href: "https://blog.csdn.net/ximen_qing"
    },{
        title: "脉脉·白小凯",
        href: "https://maimai.cn/contact/share/card?u=zvhynwxreali"
    },{
        title: "Linkin·白小凯",
        href: "https://www.linkedin.com/in/%E5%B0%8F%E5%87%AF-%E7%99%BD-27248111b?trk=profile_share_wechat&from=singlemessage&isappinstalled=0"
    }
]
